#
# Copyright (c) 2023 German Cancer Research Center (DKFZ).
#
# Distributed under the MIT License (license terms are at https://github.com/TheRoddyWMS/AlignmentAndQCWorkflows).
#
# This container only contains the base software stack installed on the DKFZ compute nodes.
# The get the workflows running, you need to additionally provide the mounts of the software
# stack:
#
#    /tbi/software/ /software /software/modules/3.2.10
#
# Image name: ghcr.io/theroddywms/dkfz_minimal:$version
#
FROM ghcr.io/theroddywms/dkfz_minimal:1.0.0

LABEL maintainer="Philip R. Kensche <p.kensche@dkfz-heidelberg.de>"

LABEL org.opencontainers.image.source="https://github.com/TheRoddyWMS/Roddy"

LABEL org.opencontainers.image.description "CentOS 7.9 container mimicking an old ODCF-DKFZ cluster node. Version 1.0.1 fixes a missing module definition path and makes the biomodal and workflows/husar modules available."

# This layer just updates the already existing modules.sh file, such that also biomodal and
# workflows/husar modules are getting available.
COPY etc/profile.d/modules.sh  /etc/profile.d/modules.sh
